# https://goreleaser.com/customization/
project_name: trumpet
before:
  hooks:
    - go mod tidy
builds:
  - main: ./main.go
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
    mod_timestamp: "{{ .CommitTimestamp }}"
    flags:
      - -trimpath
    ldflags:
      - -s -w -X main.version={{.Version}} -X main.commit={{.Commit}} -X main.date={{ .CommitDate }}

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - Merge pull request
      - Merge branch
      - go mod tidy

archives:
  - format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE*
      - README*

release:
  # Repo in which the release will be created.
  # Default is extracted from the origin remote URL.
  github:
    owner: elonzh
    name: trumpet

  # If set to true, will not auto-publish the release.
  # Default is false.
  draft: false

  # If set to true, will mark the release as not ready for production.
  # Default is false.
  prerelease: true

  # You can change the name of the GitHub release.
  # This is parsed with the Go template engine and the following variables
  # are available:
  # - ProjectName
  # - Tag
  # - Version (Git tag without `v` prefix)
  # Default is ``
  name_template: "{{.ProjectName}}-v{{.Version}}"

dockers:
  - goos: linux
    goarch: amd64
    image_templates:
      - "elonzh/trumpet:latest"
      - "elonzh/trumpet:{{ .Tag }}"
      - "elonzh/trumpet:v{{ .Major }}"
